exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('thcproducts').del()
    .then(function () {
      // Inserts seed entries
      return knex('thcproducts').insert([
        {name: 'Canna Body Cream', img_url: 'https://static.wixstatic.com/media/7026a3_1445f4039f7a4b8ca9fe5c33a05bd133~mv2.png', description: 'Our Canna Body Cream is a creamy, moisturizing lotion infused with 300mg THC. Canna lotion can be used daily to hydrate and heal your skin. The cream provides additional health & wellness benefits, such as relief from sore muscles, arthritis, various aches & pains and general skin health. DO NOT USE IF YOU ARE NURSING OR PREGNANT. KEEP OUT OF REACH OF CHILDREN AND ANIMALS.'},
        {name: 'Canna Body Butter', img_url: 'https://static.wixstatic.com/media/7026a3_336c6067d7234783822ec730aafa46ba~mv2.jpg', description: 'Our Canna Body Cream is a creamy, moisturizing lotion infused with 300mg THC. Canna lotion can be used daily to hydrate and heal your skin. The cream provides additional health & wellness benefits, such as relief from sore muscles, arthritis, various aches & pains and general skin health. DO NOT USE IF YOU ARE NURSING OR PREGNANT. KEEP OUT OF REACH OF CHILDREN AND ANIMALS.'},
        {name: 'Canna Bath Bombs', img_url: 'https://static.wixstatic.com/media/7026a3_f408407ef08f4bd3b5e69fcf88c1ac48~mv2.jpg', description: 'Fill your bathtub with hot water, drop your Canna Bomb and watch as it releases its Therapeutic Powers. THC Canna Bombs are a hard-packed mixture of dry natural ingredients that fizzes up when wet. More than just a cute round ball, our THC Canna Bombs have significant medical uses for pain, sore joints or just dry skin. Our Canna Bombs will have you, not only feeling pain free, but also relaxed! DO NOT USE IF YOU ARE NURSING OR PREGNANT. KEEP OUT OF REACH OF CHILDREN AND ANIMALS.'},
        {name: 'CannaSoap Bar', img_url: 'https://static.wixstatic.com/media/7026a3_9c97a44136e14f02825ef2f662bb6eae~mv2.jpg', description: 'Feel the rejuvenating benefits of cannabis with our all natural, hand-crafted CannaSoap! Made with the best ingredients and purest isolate, your skin and body will thank you for cleansing with this high quality product! DO NOT USE IF YOU ARE NURSING OR PREGNANT. KEEP OUT OF REACH OF CHILDREN AND ANIMALS.'},
        {name: 'Egyptian Luver', img_url: 'https://scontent.fphx1-1.fna.fbcdn.net/v/t1.0-9/31250572_10156315166502236_3943048413184000000_n.jpg?_nc_cat=0&oh=c39d5dd737a55aca8c0639ae490df97d&oe=5BE13CBA', description: 'From the creators of 420 Skincare, Egyptian Luver Erotica Cream is the perfect topical for female patients seeking to add a little spice to their lives. DO NOT USE IF YOU ARE NURSING OR PREGNANT. KEEP OUT OF REACH OF CHILDREN AND ANIMALS.'},
        {name: '420 Skincare - Starter Pack', img_url: 'https://static.wixstatic.com/media/7026a3_1445f4039f7a4b8ca9fe5c33a05bd133~mv2.png', description: 'A great way for patients to experience the line together, our 420 Starter Pack includes 1 small Canna Soap bar, 1 small Canna Bath Bomb and 1 oz. Canna Lotion all in a decorative bowl. DO NOT USE IF YOU ARE NURSING OR PREGNANT. KEEP OUT OF REACH OF CHILDREN AND ANIMALS.'}
      ]);
    });
};
